### ISSUE TITLE
ofType broken?

### ISSUE THREAD

**Issue by solenya-group** [jin-qu/jinqu#3] opened 2019-01-21 12:03 UTC
The following:

```typescript
[1,"two",3].ofType(Number)
```
Won't compile. And even if it could, you really want `number`, not `Number`.

See:  
https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html

And also:  
https://www.typescriptlang.org/play/#src=var%20x%3Anumber%3B%0Avar%20y%3ANumber%3B%0Ay%20%3D%20x%3B%20%2F%2F%20okay%20%0Ax%20%3D%20y%3B%20%2F%2F%20not%20okay%20 

Repro:
https://stackblitz.com/edit/jinqu-oftype?file=index.ts

Thinking out loud, but the possible categories of types are:

* Primitive Types
* Class Types
* Structures

The only category of types that can actually just work here are class types. The other categories don't have runtime type information. One strategy I've eventually become comfortable with in such scenarios has been to allow the caller to provide a default or "guide" type:

[1,"two",3].ofType(0) // numbers
[1,"two",3].ofType("") // strings

**Comment by umutozel** [comment] 2019-01-21 12:06
I'm on it.

**Comment by umutozel** [comment] 2019-01-21 12:29
I'm not sure why StackBlitz have trouble with that code, same works on my VS Code (TS 3.2.2).

But, passing default values are GREAT idea, it can convert query to that generic type via type inference.

I've started to think a way to implement this.

Anyway, I'm still not sure why that didn't work on StackBlitz, I was confident with the `ofType` implementation.

**Comment by umutozel** [comment] 2019-01-21 12:32
Yeah, I see it now. Multi-typed array is the problem. Works like below:

```typescript
    const arr: Array<any> = [1,"two",3]
    return div(      
      div (arr.q().ofType(Number).toArray())
    )
```

For other syntax to work, I must remove the generic constraint (new type must inherit from query type).

**Comment by solenya-group** [comment] 2019-01-21 14:01
Wondering if similar issues exist for these operators:

```typescript
elementAtOrDefault
firstOrDefault
lastOrDefault
singleOrDefault
```
If any of these operators are operating on an empty array, the type will not be known.

**Comment by solenya-group** [comment] 2019-01-21 14:10
Given that these operators were invented in the absence of nullable reference types, it might be reasonable to have "Default" to have the return type T|undefined...

**Comment by umutozel** [comment] 2019-01-21 19:14
I couldn't find a solution for `ofType` usage on a multi-typed query. I don't want to remove generic constraint. I'm open for suggestions.

But now thinking again returning the Default value might be more accurate. I always considered JavaScript value types are all nullable, so default value for all would be null. If a `cast` was called on a query, we might be able to learn default type. I'm thinking a solution.

**Comment by solenya-group** [comment] 2019-01-21 19:18
What is meant by a multi-typed query?

**Comment by umutozel** [comment] 2019-01-21 19:22
I'm not sure what is it called, I guess I made up the name.

```typescript
// implicitly typed as Array<number | string | boolean>
// this way generic constraints fail
const arr = [1, 'a', true]
arr.ofType(Number)    // fails

// if we explicitly type it as 'any', it works
const arr: Array<any> = [1, 'a', false]
arr.ofType(Number)    // works
```

**Comment by umutozel** [comment] 2019-01-21 19:26
Hmm, OK, found it. They named it 'Union Types'. My made up name is better

**Comment by solenya-group** [comment] 2019-01-24 11:46
Typescript actually has a feature called "type guards" expressly for this purpose. So you can go:

```typescript
const justNumbers = ofType ([1,"two",3], isNumber)
```
Prototype:
https://stackblitz.com/edit/oftypestructure?file=index.ts

Here's a link to the typescript spec that talks about type gaurds:
https://www.typescriptlang.org/docs/handbook/advanced-types.html

Not sure if this can be easily implemented where `ofType` can take an argument that takes either a constructor or a type guard. If that's a problem, it could always be called something like `ofTypeGuard`. Also, it might still make sense to also allow default values. E.g. `""` or `0`, so for the common cases people don't have to write `isNumber` or `isString`.

BTW, the existing version is broken with "String" (though as mentioned earlier "String" as opposed to "string" shouldn't really be used):
https://stackblitz.com/edit/jinqu-oftype

**Comment by umutozel** [comment] 2019-01-25 06:55
I fixed the problem with "String" cast.

Still considering options to support union types.
I don't want to add a function especially for union types though, I believe `IQuery<>`should not differentiate from C# `IQueryable<>`.

**Comment by umutozel** [comment] 2019-01-25 07:14
OK, I implemented your default value suggestion, and it works great! Thank you.
I misinterpreted that at first, I thought it would impact reference types, but I realized I can still get the constructor from passed default value.

Here are some tests:

```typescript
const items = ['1', 2, 'a3', 4, false, '5'];

const numbers1 = (items as any[]).asQueryable().ofType(Number).toArray();
expect(numbers1).to.deep.equal([2, 4]);
const numbers2 = items.asQueryable().ofType(0).toArray();
expect(numbers2).to.deep.equal([2, 4]);

const strings1 = (items as any[]).asQueryable().ofType(String).toArray();
expect(strings1).to.deep.equal(['1', 'a3', '5']);
const strings2 = items.asQueryable().ofType('').toArray();
expect(strings2).to.deep.equal(['1', 'a3', '5']);
```

Published 0.5.3.

By the way, I wanted to thank you again. After your interest, I get really motivated and now, after a long time jinqu and jinqu-odata are in a great state.

**Comment by solenya-group** [comment] 2019-01-25 11:05
Glad to help. There's far too many string based query languages. To me these libraries solve a very deep problem in an elegant way. Thanks for implementing the default value - it will help.

What about type guards? I use them all the time to test whether a value implements an interface, which in typescript is really valuable, as it effectively makes an interface not just a compile time but also a runtime construct. If I can use a type guard on an instance, then it's completely natural I should be able to use it on array of instances.

This should be possible:
```typescript
const justNumbers = myList.ofType (isMyInterface)
```

Currently filtering by interfaces is very verbose and not elegant like it is in C#:

```typescript
const justNumbers = myList.filter (x => isMyInterface(x)).cast<IMyInterface>()
```

**Comment by umutozel** [comment] 2019-01-25 11:27
I wanted to keep `ofType` parameter as only a `Constructor<T>`. So we might be able to send the type info through the wire, maybe using the class name. This way, `ofType`would be usable for Linquest too.

I can't think of any way for a type guard to be serializable.

Maybe, we can make type guards only usable within jinqu. 
When the argument is not a .ctor, Linquest can throw an error.

**Comment by solenya-group** [comment] 2019-01-25 12:22
> Maybe, we can make type guards only usable within jinqu.
That's fine.

**Comment by umutozel** [comment] 2019-01-25 13:45
I did a weird trick and it's working.
Here is the code from test:

```typescript
// type guard
function isProduct(item): item is IProduct {
    return item && item.category != null;
}

const orderProducts = (orders as (IOrder | IProduct)[]).concat(products);
const products2 = orderProducts.ofType(isProduct).toArray();

expect(products).to.be.deep.eq(products2);
```

I couldn't find a safe way to determine if a function is .ctor or a predicate. So I've tried to call it in a try..catch, if it's a .ctor, it would return undefined (or throw error for ES6 classes).

```typescript
try {
    if (type(i))
        yield i;
}
catch (e) { 
    // ignored. might throw error for ES6 classes
}
```

I'm happy with it. Published 0.5.4.

By the way, type guards will only work for reference types. We should use default values for primitive types.

**Comment by solenya-group** [comment] 2019-01-25 14:43
I agree the solution requires a bit of hack to work around typescript/javascript's type system. Here's one way to make `isNumber` work:

https://stackblitz.com/edit/oftypestructure?file=index.ts

I've previously used converting functions to strings quite robustly; despite not officially being a standard, the outputs across browsers even including IE are reliable & similar, and I think so many people are now depending on such behaviour that the browsers can't change it. (Note you might already be doing this kind of thing in jinqu; haven't looked at that level of detail of your implementation).

The advantage of ensuring type guards always work, is that people can more easily write code that operates at a meta-level.

**Comment by solenya-group** [comment] 2019-01-25 14:46
Note with this approach you'd need one more type filter that let you pass in default values for ""/0. I just figured that bit was obvious so left it out.

**Comment by solenya-group** [comment] 2019-01-25 14:56
Pasting in the core part of the code here:

```typescript
type TypePredicate<T> = (t: any) => t is T
type TypeConstructor<T> = new() => T
type TypeFilter<T> = TypePredicate<T> | TypeConstructor<T>

const isConstructor = <T> (filter: TypeFilter<T>) : filter is TypeConstructor<T> =>
  ("" + filter).indexOf ("return") == -1

function ofType<T,U> (list: T[], type: TypeFilter<U>) {

  const filtered: U[] = []
  const filter = isConstructor (type) ?
    (x: T) => x instanceof type :
    (x: T) => type(x)
  
  for (var x of list)    
    if (filter(x))
      filtered.push (x as any as U)

  return filtered
}

class Elephant { }

const isNumber = (x: any): x is number =>
    typeof x === "number"

const justNumbers = ofType ([1,"two",3], isNumber)
const justElephants = ofType ([1, new Elephant(), 3], Elephant)
```

**Comment by umutozel** [comment] 2019-01-26 11:09
I've used stringifying functions heavily, especially on jokenizer project, which jinqu depends on.
This way might be a less hack, but I can't think a scenario which `try..catch` would fail. It's not that different than relying browsers to be consistent for `function.toString` implementations. Also, with ES5+ environments, we might get arrow functions instead of functions (without return).

Btw, if something still not working as expected with this approach or it's really a deal breaker for you, of course I'll consider other implementations (like yours). Otherwise I tend to keep it this way,

**Comment by umutozel** [comment] 2019-01-26 12:55
I never do it, that's why I didn't think of it, but .ctor might have side-effect (like counting instances etc..). And after remembering that arrow functions don't have a prototype property, I accept it's better to implement it via stringifying.
Will do it tonight.

**Comment by umutozel** [comment] 2019-01-26 20:36
Done, published 0.5.6. Just added a little regex lookup instead of an `indexOf` to avoid a very edge case. 

One might use 'return' in a .ctor without returning, like assigning a value to a property.

```typescript
class Movie {

    constructor() {
        this.name = 'return of the jedi';
    }

    name: string;
}
```
Here is the lookup:

```javascript
!/return(?=([^"]*"[^"]*")*[^"]*$)/.test('' + func)
```
I know, this is very unlikely but I feel better this way :)

Closing for now, but would be happy to hear feedback.

**Closed as completed by umutozel** 2019-01-26 20:36 UTC

**Comment by solenya-group** [comment] 2019-01-27 18:47
I somehow have got confused here. I just tested `isNumber` here expecting it to work and it fails silently:

https://stackblitz.com/edit/jinqu-oftype

Just to be clear, my assumptions were:

1) For primitive types, *both* default values and type guards should work. Why should type guards work for primitive types if you can just use a default value anyway? Because:
    a) people write meta-code where they don't want to have to special case primitive types.
    b) from a usability point of view, some people might not at first realize you can pass a default value to `ofType` like `0` for primitive types, try passing a type guard in, and then get confused when it doesn't work.
   c) semantically, according to the purpose of the function, it's broken if primitive type guards don't work.
2) It's possible at runtime to differentiate between constructors and type guards. The prototype demonstrated the basic idea works; I thought you'd elaborated on that with a better more robust solution than what I had (which is partly why I'm confused).

BTW, I really appreciate all the improvements you're making; don't want to come across as always raising problems!

**Comment by umutozel** [comment] 2019-01-27 19:47
1. Yeah, I had changed the code for guards to work for both primitives and references, I believe a few iteration back. I agree, that way is more intuitive.

2. I didn't improve your idea, just accepted eventually, after realizing my mistake of calling a .Ctor. I couldn't think of side-effects at first. And after realizing my mistake, I couldn't keep that code, yours is the best alternative. Also my first objection to your code was arrow functions, they don't contain 'return' (for expressions). But I remembered arrow functions don't have a 'prototype' property like other functions (I had written similar code before so it took time for me to remember). By adding a regex lookup (instead of a 'indexOf'), I just wanted to make sure that found 'return' is a keyword, not in a string. Bu I gave up, RegEx got really complicated, I kept finding scenarios that won't work. Sooo finally removed all and basically implemented your code a few hours before your last message, just didn't commit it (a few minutes back I did).

Of course not, I can't tell how much I like this, -brain storming, ideas, improvements- and WE are making improvements :) You had an amazing impact on jinqu, I am really grateful.

**Comment by umutozel** [comment] 2019-01-27 19:49
Here is the implementation:

```typescript
ofType<TResult extends T>(type: Ctor<TResult> | TResult | TypePredicate<TResult>): IQuery<TResult> {
    if (type == null) throw new Error('Value cannot be null. Parameter name: type');

    let ctor = <Ctor<TResult>>type;
    if (typeof type !== 'function') {
        ctor = <any>type.constructor;
    }
    else if (!isCtor(type)) {
        return this.create(QueryPart.guard(<any>type));
    }
    
    return (<IQuery<TResult>>this.create(QueryPart.ofType(ctor))).cast(ctor);
}

function isCtor(func) {
    if (func.prototype == null) return false;

    return !('' + func).includes('return');
}
```
Now there is a different handler method for guards.

**Comment by umutozel** [comment] 2019-01-27 19:55
Just looking for validation, If you say searching for 'return' in function body would be enough (ignoring 'return's in strings), I can publish a new npm.

**Comment by solenya-group** [comment] 2019-01-28 13:04
So looking here:
https://stackoverflow.com/questions/367768/how-to-detect-if-a-function-is-called-as-constructor

It seems my assumption '2' was incorrect. So there isn't a full-proof approach that can work in all browsers (i.e. IE).

Stepping back a bit, I'm wondering whether the real problem is we're being too strict in terms of having a 1-1 correspondence between LINQ in C# and LINQ in Typescript. Perhaps the goal should be: do things the C# way where *possible*, but have a Typescript way of doing things where *necessary*. Or to put it another way, like with any translation, some things translate naturally, and some things need to be modified to respect the idioms and constraints of the target language.

Applying that principle, we could say that due to the Javascript/Typescript type system, the only robust solution in this case is to provide a separately named method for type guards. Maybe:

`ofGuardedType`

This would work 100% of the time, be quite easy to discover with autocomplete (it would appear right next to `ofType`), and would be utterly clear and unambiguous as to its purpose. `ofType` would work for just constructors and default values (where that has an reasonably strong correspondence with the C# way of doing things).

**Comment by umutozel** [comment] 2019-01-28 15:34
I aggree completely, you probably realized, I implemented half of it already; created a new QueryPart, not supported by LINQ, and named it `guard`. So, when Linquest sees this Part it throws an error because it's not Linq. But creating a new method for it `ofGuardedType` (it's the best possible name), and adding this to a new interface, like `IArrayQuery` would be great.

**Comment by umutozel** [comment] 2019-01-28 16:49
I've completed this but will look at #12 first, before publishing a package.

**Comment by solenya-group** [comment] 2019-01-28 22:27
Just tested ofGuardedType and it works but for some reason ofType now seems broken (probably something really trivial).

https://stackblitz.com/edit/jinqu-oftype

I'm about to PR some doc updates.

**Comment by umutozel** [comment] 2019-01-29 05:17
Probably missing something on unit tests, just reproduced on local. Back soon.

**Comment by umutozel** [comment] 2019-01-29 05:30
Fixed with 0.5.8. 
Occurs when item is primitive but parameter is not (like Order). Ends up calling .Ctor for type conversion. Added some tests that cover this.
Great catch!

**Comment by solenya-group** [comment] 2019-01-29 15:55
`ofGuardedType` appears to be typed to `any` (should be `TResult`). Should be an easy fix though. The definition seems to currently be:

```typescript
export interface IArrayQuery {
    ofGuardedType<TResult>(checker: TypePredicate<TResult>): any;
}
```

**Comment by umutozel** [comment] 2019-01-29 22:17
I forgot to add return type explicitly, so tsc added any as default. Fixed it.

Btw, as you realized I wanted to implement `ofGuardedType` like Entity Framework did with Include. There isn't an extension method for Include on IQueryable, you could only call it on EntityQuery or EntitySet. But there is a difference,`ofGuardedType` is on the base class, so my resistance is futile, it will be visible. 
I guess it must be visible, since there is no explicit interface implementation with TypeScript. I'm gonna add `ofGuardedType` to IQuery.

**Comment by umutozel** [comment] 2019-01-30 10:57
Published new packages with .ts and .js.map files.
